version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "4848:4848"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: authtest
      DB_USER: dynamic
      DB_PASSWORD: dynamic
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: authtest
      POSTGRES_USER: dynamic
      POSTGRES_PASSWORD: dynamic
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db-data:
